apiVersion: v1
kind: Service
metadata:
  name: cnkidemo
  namespace: kubesphere-sample-dev
  labels:
    app: mavendemo
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30090 #service对外开放端口
  selector:
    app: mavendemo
